name: CI

on: push

jobs:
  mypy:
    name: 'pip install'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: chart_hacking
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -e . --upgrade-strategy eager -r requirements.txt
      - name: Run piker
        run: piker 
